name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: python -m playwright install --with-deps

      - name: Run tests with Allure results
        run: pytest -s -v --alluredir=allure-results

      # Генерация Allure-отчёта и публикация на gh-pages
      - name: Generate and publish Allure report
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          github_token: ${{ secrets.GITHUB_TOKEN }}
